{% set name = "proto-plus" %}
{% set version = "1.17.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/proto-plus-{{ version }}.tar.gz
  sha256: ebced9a550a4236ec652a4988bf68e5c7da613b001165405975dd548c844e5cd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - protobuf >=3.12.0
    - python

test:
  imports:
    - proto
    - proto.marshal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/proto-plus-python.git
  summary: Beautiful, Pythonic protocol buffers.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tswast
