{% set name = "proto-plus" %}
{% set version = "1.24.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/proto-plus-{{ version }}.tar.gz
  sha256: 30b72a5ecafe4406b0d339db35b56c4059064e69227b8c3bda7462397f966445

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - protobuf >=3.19.0,<6.0.0dev

test:
  imports:
    - proto
    - proto.marshal
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/proto-plus-python
  summary: Beautiful, Pythonic protocol buffers.
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/googleapis/proto-plus-python
  doc_url: https://proto-plus-python.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - xylar
    - tswast
