{% set name = "proto-plus" %}
{% set version = "1.25.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: fbb17f57f7bd05a68b7707e745e26528b0b3c34e378db91eef93912c54982d91

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - protobuf >=3.19.0,<6.0.0dev

test:
  imports:
    - proto
    - proto.marshal
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/googleapis/proto-plus-python
  summary: Beautiful, Pythonic protocol buffers.
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/googleapis/proto-plus-python
  doc_url: https://proto-plus-python.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - xylar
    - tswast
