schema_version: 1

context:
  name: proto-plus
  version: "1.28.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 26d843eb99c1e32fdf1d20ff0faae56607f7748fe774acf9ecd5cfe6c6472501

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - protobuf >=4.25.8,<8.0.0

tests:
  - python:
      imports:
        - proto
        - proto.marshal
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Beautiful, Pythonic protocol buffers.
  license: Apache-2.0
  license_file: LICENSE
  homepage: https://github.com/googleapis/google-cloud-python/tree/main/packages/proto-plus
  repository: https://github.com/googleapis/google-cloud-python/tree/main/packages/proto-plus
  documentation: https://proto-plus-python.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - xylar
    - tswast
